# These are required for the tests

source 'http://rubygems.org'

gem 'iron_worker'

group :test do
  gem 'rack', '>= 3.0.0'
  gem 'test-unit'
  gem 'jeweler2'
  gem 'zip'
  gem 'rest'
  gem 'typhoeus'
  gem 'uber_config'

  gem 'simple_record'
  gem 'activerecord', '>= 6.1.7.1'
  gem 'activesupport', '>= 6.1.7.3'
  gem 'simple_record'
  gem 'dropbox', '1.2.3'
  gem 'mongoid_i18n'
  gem 'signature'
  gem 'pusher'
  gem 'carrierwave', '>= 1.3.2'
  gem 'aws-s3'
  gem 'mechanize', '>= 2.8.5', '>= 2.8.5'
  gem 'mail', '>= 2.5.5'
  gem 'timecop'
  gem 'fog', '>= 1.14.0'
  gem 'logglier'
#gem 'mysql2'
  gem 'mini_fb'
  gem 'iron_mq'
  gem 'prawn'
  gem 'pdf-reader'
  gem 'concur'
  gem 'mechanize'
end
