# These are required for the tests

source 'http://rubygems.org'

gem 'iron_worker'

group :test do
  gem 'rack'
  gem 'test-unit'
  gem 'jeweler2'
  gem 'zip'
  gem 'rest'
  gem 'typhoeus'
  gem 'uber_config'

  gem 'simple_record'
  gem 'activerecord', '>= 3.2.14'
  gem 'activesupport', '>= 5.2.4.3'
  gem 'simple_record'
  gem 'dropbox', '1.2.3'
  gem 'mongoid_i18n', '>= 0.5.1'
  gem 'signature'
  gem 'pusher'
  gem 'carrierwave', '>= 0.6.2'
  gem 'aws-s3'
  gem 'mechanize'
  gem 'mail'
  gem 'timecop'
  gem 'fog'
  gem 'logglier'
#gem 'mysql2'
  gem 'mini_fb'
  gem 'iron_mq'
  gem 'prawn'
  gem 'pdf-reader'
  gem 'concur'
  gem 'mechanize'
end
